### ISSUE TITLE
Error 404 when transcoding flac to mp3

### ISSUE THREAD

**Issue by stncrn** [Sonerezh/sonerezh#261]
Hello, 

I am facing an issue since I upgraded from 1.1.1 to 1.1.3. I also tried installed 1.1.3 from scratch, with a new database, an the issue is still the same.

My transcoding settings looks like this : 

![image](https://cloud.githubusercontent.com/assets/25079376/21889532/a597ee4e-d8c9-11e6-9ceb-f9ed4f22f7f0.png)
So I want my mp3s to be played directly, and my flacs to be transcoded to mp3.

When I try to play an mp3, everything goes fine : 

![image](https://cloud.githubusercontent.com/assets/25079376/21889630/3820d564-d8ca-11e6-8cf7-4843679af950.png)

But when I try to play a flac, I got a 404 error :

![image](https://cloud.githubusercontent.com/assets/25079376/21889716/a2eb7f98-d8ca-11e6-8795-437410b0d9cc.png)

When trying to access directly the song at https://my.host/songs/download/2829, I get the same 404 error :

![image](https://cloud.githubusercontent.com/assets/25079376/21889759/d1f1e8ea-d8ca-11e6-9145-38791ecd99d2.png)

When I do the same with an mp3, the download of the mp3 file is working properly.

The Apache logs aren't showing anything useful, except the same 404 error.

Do any of you have an idea to push the troubleshooting further?
For the moment, I'm reverting to the 1.1.1 version, which is still working properly.

Edit : When looking at the admin panel, I can see that the flac songs aren't transcoded at all :

![image](https://cloud.githubusercontent.com/assets/25079376/21890918/68cf4852-d8d0-11e6-95f5-d7d87db2c0ab.png)

**Comment by atomiix** [comment]
Hi @stncrn,

I'm pretty sure that's a bug recently fixed by #259. 

This fix will be released in the next Sonerezh version but if you can't wait you can either choose to transcode to ogg format or use the development branch of Sonerezh which already contain the fix.

**Comment by stncrn** [comment]
You are definitely right. I modified the SongsController.php file as in the commit and the transcoding is working for most of the flacs now.
So, thanks for the fix.


But I still have the issue with songs with non-ASCII characters in their path/filename. The HTTP code is now 200, but the file is not trancoded, as avconv seems to loose the special characters :

![image](https://cloud.githubusercontent.com/assets/25079376/21897645/8b4af7cc-d8ea-11e6-949a-ca05024f71b0.png)

**Comment by stncrn** [comment]
I just found out that @bruce965 was encountering the same [issue with non-ASCII characters](https://github.com/Sonerezh/sonerezh/issues/263). 

Implementing his fix (adding `setlocale(LC_CTYPE, 'C.UTF-8');` just before the call to `passthru`) definitely solved this problem.

I'm closing this issue, as the fix and root cause is much more detailed in his thread.

Thanks anyway to the devs for their work, and to the community for their support/bugfixes.
